spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: report-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:report_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:healntrack1234}
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    consumer:
      group-id: report-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: latest
      enable-auto-commit: false
    listener:
      ack-mode: record
      concurrency: ${KAFKA_CONCURRENCY:3}

server:
  port: ${SERVER_PORT:8008}

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/