name: report

on:
  push:
    branches: [develop, main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables based on branch
        shell: bash
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "HOST=${{ secrets.GCP_VM_HOST_PROD }}" >> $GITHUB_ENV

            if [ -n "${{ secrets.PORT_PROD }}" ]; then
              echo "PORT=${{ secrets.PORT_PROD }}" >> $GITHUB_ENV
            else
              echo "PORT=8008" >> $GITHUB_ENV
            fi

            echo "DB_HOST=${{ secrets.DB_HOST_PROD }}" >> $GITHUB_ENV
            echo "DB_PORT=${{ secrets.DB_PORT_PROD }}" >> $GITHUB_ENV
            echo "DB_NAME=${{ secrets.DB_NAME_PROD }}" >> $GITHUB_ENV
            echo "DB_USER=${{ secrets.DB_USER_PROD }}" >> $GITHUB_ENV
            echo "DB_PASS=${{ secrets.DB_PASS_PROD }}" >> $GITHUB_ENV

            echo "KAFKA_HOST=${{ secrets.KAFKA_HOST_PROD }}" >> $GITHUB_ENV
            echo "KAFKA_PORT=${{ secrets.KAFKA_PORT_PROD }}" >> $GITHUB_ENV

            echo "EUREKA_HOST=${{ secrets.EUREKA_HOST_PROD }}" >> $GITHUB_ENV
            echo "EUREKA_PORT=${{ secrets.EUREKA_PORT_PROD }}" >> $GITHUB_ENV

            echo "PUBLIC_HOST=${{ secrets.PUBLIC_HOST_PROD }}" >> $GITHUB_ENV
          else
            echo "HOST=${{ secrets.GCP_VM_HOST }}" >> $GITHUB_ENV

            if [ -n "${{ secrets.PORT }}" ]; then
              echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV
            else
              echo "PORT=8008" >> $GITHUB_ENV
            fi

            echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
            echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
            echo "DB_PASS=${{ secrets.DB_PASS }}" >> $GITHUB_ENV

            echo "KAFKA_HOST=${{ secrets.KAFKA_HOST }}" >> $GITHUB_ENV
            echo "KAFKA_PORT=${{ secrets.KAFKA_PORT }}" >> $GITHUB_ENV

            echo "EUREKA_HOST=${{ secrets.EUREKA_HOST }}" >> $GITHUB_ENV
            echo "EUREKA_PORT=${{ secrets.EUREKA_PORT }}" >> $GITHUB_ENV

            echo "PUBLIC_HOST=${{ secrets.PUBLIC_HOST }}" >> $GITHUB_ENV
          fi

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

      - name: Deploy to VM
        run: |
          ssh ${{ secrets.GCP_VM_USER }}@"$HOST" << EOF
            set -e
            cd ./healntrack-report
            git checkout ${GITHUB_REF_NAME}
            git pull

            sudo docker container prune -f || true
            sudo docker image prune -af || true
            sudo docker builder prune -af || true
            sudo docker volume prune -f || true

            sudo docker build -t report-service .

            sudo docker stop report-service || true
            sudo docker rm report-service || true

            sudo docker run -d --name report-service \
              -p "$PORT:$PORT" \
              -e PORT="$PORT" \
              -e DB_HOST="$DB_HOST" \
              -e DB_PORT="$DB_PORT" \
              -e DB_NAME="$DB_NAME" \
              -e DB_USER="$DB_USER" \
              -e DB_PASS="$DB_PASS" \
              -e KAFKA_HOST="$KAFKA_HOST" \
              -e KAFKA_PORT="$KAFKA_PORT" \
              -e EUREKA_HOST="$EUREKA_HOST" \
              -e EUREKA_PORT="$EUREKA_PORT" \
              -e PUBLIC_HOST="$PUBLIC_HOST" \
              report-service
          EOF
